# Generated by Django 4.2.6 on 2023-10-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("stock", models.IntegerField()),
                ("image", models.CharField(max_length=3000)),
            ],
        ),
    ]
